# Generated by Django 3.2.4 on 2021-06-11 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, null=True)),
                ('name', models.CharField(blank=True, max_length=140)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dir/path/')),
                ('room_text', models.TextField(blank=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.adventure')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(blank=True, max_length=140)),
                ('associated_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='adventure.room')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventure.room')),
            ],
        ),
    ]
