# Generated by Django 3.2.4 on 2021-06-17 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adventure', '0003_room_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='order',
        ),
        migrations.AddField(
            model_name='adventure',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
